server:
  port: 9090
spring:
  profiles:
    active: default

  datasource:
    url: jdbc:mysql://localhost:3306/chapter_97
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 또는 create, create-drop (환경에 따라 선택)
    show-sql: true  # SQL 쿼리를 콘솔에 출력

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher